### ISSUE TITLE
请问下可以改个centos可用的版本吗？

### ISSUE THREAD

**Issue by sakurawill** [L-codes/ltproxy#1]
脚本好像是用dash写的，centos7的shell用的是bash，会出现错误。
![微信截图_20240131114205](https://github.com/L-codes/LTProxy/assets/6317873/bc2f67ef-6d94-4f10-93e2-3a84dc51d0dd)

**Comment by L-codes** [comment]
不是的，这是ruby编写的，运行环境需要安装下面3个外部依赖

参考 https://github.com/L-codes/LTProxy?tab=readme-ov-file#usage
```ruby
0. 需安装好 proxychains4 和 ipt2socks 的环境
   $ command -v ruby proxychains4 ipt2socks  # 确保 shell 环境都能找到
```

**Comment by sakurawill** [comment]
解决了，原来是centos7用yum安装的ruby版本只有2.0，更新ruby版本后可以用了，谢谢。
