### ISSUE TITLE
当 socks 服务开在本地接口地址时，会递归访问无法正常使用

### ISSUE THREAD

**Issue by sakurawill** [L-codes/ltproxy#2]
0. 需安装好 ruby、proxychains4 和 ipt2socks 的环境 (ruby 需要 3.0+)
   $ command -v ruby proxychains4 ipt2socks  # 确保 shell 环境都能找到
在centos7都装好了，ruby也是3.0版本make安装的，proxychains4 4.17， ipt2socks也是git最新的，指令都可以运行跑起来，但代理没生效

**Comment by L-codes** [comment]
可以看看你的yml配置吗？

**Comment by sakurawill** [comment]
![微信截图_20240202164333](https://github.com/L-codes/LTProxy/assets/6317873/79d64b7c-2e92-4c79-b858-c5a788a15058)

**Comment by L-codes** [comment]
确实，我测试发现是如果 socks 服务开在本地环境的话，会出现循环访问的问题，我想一下修复方案

**Comment by sakurawill** [comment]
![image](https://github.com/L-codes/LTProxy/assets/6317873/875971e7-878d-45de-855e-d822cae72d00)
但是我外网机走代理进内网又可以，内网机走代理出外网才不行，这张图的是可以的，我外网机ip是30段，可以走代理访问10段的，就上面那张无法走0段的代理去访问互联网，我直接用proxychains4+curl是可以的，但用ltproxy就不行了

**Comment by L-codes** [comment]
目前测试到的是 socks 开在使用 ltproxy 的服务器本机透明代理就不行

**Comment by L-codes** [comment]
搞清楚了，是因为你socks开在本地的话，socks的请求也会进入透明代理，透明代理又给了socks，流量循环递归无法使用。目前的解决方案是你的socks 需要使用本地的 ltproxy 用户启动，如: `sudo -u ltproxy <socks 启动命令>`

**Comment by INT2ECALL** [comment]
牛逼！

**Comment by sakurawill** [comment]
> 搞清楚了，是因为你socks开在本地的话，socks的请求也会进入透明代理，透明代理又给了socks，流量循环递归无法使用。目前的解决方案是你的socks 需要使用本地的 ltproxy 用户启动，如: `sudo -u ltproxy <socks 启动命令>`
注意当 `ltproxy` 和 `socks` 的服务运行在一个主机上的话，`socks` 的服务需要使用 `ltproxy` 用户运行，如: `sudo -u ltproxy ./socks5 -l xxxx`
没太明白这句，我socks5代理是别的服务器，不是跟ltproxy运行在同一台机的吖，

> ![微信截图_20240202164333](https://private-user-images.githubusercontent.com/6317873/301783177-79d64b7c-2e92-4c79-b858-c5a788a15058.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDA3NDQsIm5iZiI6MTcwNzA0MDQ0NCwicGF0aCI6Ii82MzE3ODczLzMwMTc4MzE3Ny03OWQ2NGI3Yy0yZTkyLTRjNzktYjg1OC1jNWE3ODhhMTUwNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDRUMDk1NDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTRjZmJiMDliN2E5MDk2ZGZhYWJjMTg0M2YyNTk2Nzc5OWE5ZDhiZTk0NGNmNzkzYzAyNjMwYzdmNjk3MmM2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kaFEc-ZKcj0HXsoq8_xR7EbioaUlMfJf9TTogiYiyng)

就像这里，我使用的ltproxy机是0.123，socks5代理是0.249，这不是在同一台机上的吖

**Comment by L-codes** [comment]
那你的具体配置可以脱敏后提供一下吗？ 我前面以为是同主机

**Comment by sakurawill** [comment]
> ![微信截图_20240202164333](https://private-user-images.githubusercontent.com/6317873/301783177-79d64b7c-2e92-4c79-b858-c5a788a15058.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDQ2ODUsIm5iZiI6MTcwNzA0NDM4NSwicGF0aCI6Ii82MzE3ODczLzMwMTc4MzE3Ny03OWQ2NGI3Yy0yZTkyLTRjNzktYjg1OC1jNWE3ODhhMTUwNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDRUMTA1OTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmZDAzZjVhODAxMmE4YWFhZDE4Mzc5MWQxMTFiYmIxOWViMDQ0OTU0N2VmYzViNmMwNDliZDg0Y2FjZTNiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xM6tG7tW3GC6FAOSIAjYMSCKCQwHKMlXnXFc1lNJHvY)

具体配置就是这图里的，然后我这台机的ip是192.168.0.123

**Comment by L-codes** [comment]
图片看不到 是前面两个图的第几个呀？

**Comment by sakurawill** [comment]
rules:
  - proxies:
      - direct
    target:
      - 192.168.*.*
      - 10.*.*.*

  - proxies:
      - socks5 192.168.0.249 27018
    target:
      - extranet
我使用ltproxy的机器ip是192.168.0.123

**Comment by L-codes** [comment]
我测试了你的配置是没有问题的，建议检查一下 `socks5 192.168.0.249 27018` 是否正常

**Comment by sakurawill** [comment]
> 我测试了你的配置是没有问题的，建议检查一下 `socks5 192.168.0.249 27018` 是否正常

端口是正常的哦，我直接用proxychains4 加curl https://www.baidu.com可以出内容，但开ltproxy start直接用curl  https://www.baidu.com就卡在那然后提示无法连接

**Comment by L-codes** [comment]
192.168.0.249 的网关不是 192.168.0.123 吧？

**Comment by sakurawill** [comment]
不是，网关是192.168.0.1

**Comment by L-codes** [comment]
查看一下 netfilter 的配置情况 `iptables -L -n -v -t nat`

查看一下进程的情况 `ps aux |grep ipt2socks`

**Comment by sakurawill** [comment]
Chain LLTPROXY (2 references)
 pkts bytes target     prot opt in     out     source               destination         
 2916  148K RETURN     tcp  --  *      *       0.0.0.0/0            192.168.0.0/16      
    0     0 RETURN     tcp  --  *      *       0.0.0.0/0            10.0.0.0/8          
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/8           
    0     0 RETURN     all  --  *      *       0.0.0.0/0            10.0.0.0/8          
    0     0 RETURN     all  --  *      *       0.0.0.0/0            100.64.0.0/10       
    0     0 RETURN     all  --  *      *       0.0.0.0/0            127.0.0.0/8         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            169.254.0.0/16      
    0     0 RETURN     all  --  *      *       0.0.0.0/0            172.16.0.0/12       
    0     0 RETURN     all  --  *      *       0.0.0.0/0            192.168.0.0/16      
    0     0 RETURN     all  --  *      *       0.0.0.0/0            198.18.0.0/15       
    0     0 RETURN     all  --  *      *       0.0.0.0/0            224.0.0.0/4         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            240.0.0.0/4         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            redir ports 60634
[root@localhost ~]# ps aux |grep ipt2socks
root        3153  0.0  0.0   6656  2304 pts/0    S+   14:52   0:00 grep --color=auto ipt2socks

**Comment by L-codes** [comment]
原因是你的 *ipt2socks* 没有启动，执行 `ipt2socks --help` 看看是否已经安装正常并配置到环境变量中了

**Comment by sakurawill** [comment]
[root@localhost ~]# ps aux |grep ipt2socks
root        3153  0.0  0.0   6656  2304 pts/0    S+   14:52   0:00 grep --color=auto ipt2socks
[root@localhost ~]# ipt2socks --help
usage: ipt2socks <options...>. the existing options are as follows:
 -s, --server-addr <addr>           socks5 server ip, default: 127.0.0.1
 -p, --server-port <port>           socks5 server port, default: 1080
 -a, --auth-username <user>         username for socks5 authentication
 -k, --auth-password <passwd>       password for socks5 authentication
 -b, --listen-addr4 <addr>          listen ipv4 address, default: 127.0.0.1
 -B, --listen-addr6 <addr>          listen ipv6 address, default: ::1
 -l, --listen-port <port>           listen port number, default: 60080
 -S, --tcp-syncnt <cnt>             change the number of tcp syn retransmits
 -c, --cache-size <size>            udp context cache maxsize, default: 256
 -o, --udp-timeout <sec>            udp context idle timeout, default: 60
 -j, --thread-nums <num>            number of the worker threads, default: 1
 -n, --nofile-limit <num>           set nofile limit, may need root privilege
 -u, --run-user <user>              run as the given user, need root privilege
 -T, --tcp-only                     listen tcp only, aka: disable udp proxy
 -U, --udp-only                     listen udp only, aka: disable tcp proxy
 -4, --ipv4-only                    listen ipv4 only, aka: disable ipv6 proxy
 -6, --ipv6-only                    listen ipv6 only, aka: disable ipv4 proxy
 -R, --redirect                     use redirect instead of tproxy for tcp
 -r, --reuse-port                   enable so_reuseport for single thread
 -w, --tfo-accept                   enable tcp_fastopen for server socket
 -W, --tfo-connect                  enable tcp_fastopen for client socket
 -v, --verbose                      print verbose log, affect performance
 -V, --version                      print ipt2socks version number and exit
 -h, --help                         print ipt2socks help information and exit

**Comment by L-codes** [comment]
你手工启动 `ipt2socks -R -n 9999 -j 50 -l 60634 -u ltproxy -s 192.168.0.249 -p 27018` 看看是否报错，不报错的话测试一下透明代理是否已经生效

**Comment by sakurawill** [comment]
[root@localhost ~]# ipt2socks -R -n 9999 -j 50 -l 60634 -u ltproxy -s 192.168.0.249 -p 27018
2024-02-05 15:14:20 INF: [main] server address: 192.168.0.249#27018
2024-02-05 15:14:20 INF: [main] listen address: 0.0.0.0#60634
2024-02-05 15:14:20 INF: [main] listen address: ::#60634
2024-02-05 15:14:20 INF: [main] udp cache maximum size: 256
2024-02-05 15:14:20 INF: [main] udp socket idle timeout: 60
2024-02-05 15:14:20 INF: [main] number of worker threads: 50
2024-02-05 15:14:20 INF: [main] enable tcp transparent proxy
2024-02-05 15:14:20 INF: [main] enable udp transparent proxy
2024-02-05 15:14:20 INF: [main] use redirect instead of tproxy
2024-02-05 15:14:20 ERR: [set_ip_transparent] setsockopt(153, IP_TRANSPARENT): Operation not permitted
2024-02-05 15:14:20 ERR: [set_ip_transparent] setsockopt(154, IPV6_TRANSPARENT): Operation not permitted

**Comment by L-codes** [comment]
使用正常？

**Comment by sakurawill** [comment]
不正常，[set_ip_transparent] setsockopt(153, IP_TRANSPARENT): Operation not permitted应该跟这里有关，但手动输指令proxychains4 curl www.baidu.com可以走代理正常访问

**Comment by L-codes** [comment]
这个是开启TPROXY的 跟这个应该没关的，这个报错你也可以通过下面命令解决：
```bash
setcap cap_net_bind_service,cap_net_admin+ep `which ipt2socks`
```

重新启动 `ipt2socks -R -n 9999 -j 50 -l 60634 -u ltproxy -s 192.168.0.249 -p 27018 -v` 再测试是否能使用，看看输出什么日志

**Comment by sakurawill** [comment]
[root@localhost ~]# setcap cap_net_bind_service,cap_net_admin+ep `which ipt2socks`
[root@localhost ~]# ipt2socks -R -n 9999 -j 50 -l 60634 -u ltproxy -s 192.168.0.249 -p 27018 -v
2024-02-06 08:39:38 INF: [main] server address: 192.168.0.249#27018
2024-02-06 08:39:38 INF: [main] listen address: 0.0.0.0#60634
2024-02-06 08:39:38 INF: [main] listen address: ::#60634
2024-02-06 08:39:38 INF: [main] udp cache maximum size: 256
2024-02-06 08:39:38 INF: [main] udp socket idle timeout: 60
2024-02-06 08:39:38 INF: [main] number of worker threads: 50
2024-02-06 08:39:38 INF: [main] enable tcp transparent proxy
2024-02-06 08:39:38 INF: [main] enable udp transparent proxy
2024-02-06 08:39:38 INF: [main] use redirect instead of tproxy
2024-02-06 08:39:38 INF: [main] verbose mode (affect performance)
重启后错误消除了，但还是不能通过代理访问

**Comment by L-codes** [comment]
你尝试但还是不能通过代理访问，那上面的 ipt2socks 进程上输出也没变化？还是上面那样？应该是 ltproxy 的配置又变了 `iptables -t nat -L -n `查看一下

**Comment by sakurawill** [comment]
应该是域名问题，ltproxy启用后域名还是无法访问，但通过ip可以访问，域名解析不走代理所以出问题了

**Comment by L-codes** [comment]
是的，目前利用的是 iptables 的方式进行透明代理，暂无法让域名走socks，域名在本地解析，你也可以给 /etc/hosts 添加静态绑定，现在是可以正常，那我先关闭该 `issue` 了，有问题再重新打开
